version: '3.8'

services:
  motorgear-monitor:
    build:
      context: .
    container_name: motorgear_monitor
    restart: always
    ports:
      - "8082:80"
    networks:
      - monitor-network

networks:
  monitor-network:
    driver: bridge
